export enum TokenType {
  NEWLINE = 'NEWLINE',
  INDENT = 'INDENT',
  DEDENT = 'DEDENT',
  EOF = 'EOF',

  HEADING = 'HEADING',
  HEADING_MARKER = 'HEADING_MARKER',

  BULLET_LIST = 'BULLET_LIST',
  ORDERED_LIST = 'ORDERED_LIST',
  TASK_LIST = 'TASK_LIST',
  DEFINITION = 'DEFINITION',

  BLOCKQUOTE = 'BLOCKQUOTE',
  INDENTATION = 'INDENTATION',
  CODE_BLOCK = 'CODE_BLOCK',
  HORIZONTAL_RULE = 'HORIZONTAL_RULE',
  FRONTMATTER = 'FRONTMATTER',

  TRIPLE_COLON_START = 'TRIPLE_COLON_START',
  TRIPLE_COLON_END = 'TRIPLE_COLON_END',

  DOUBLE_BRACKET_START = 'DOUBLE_BRACKET_START',
  DOUBLE_BRACKET_END = 'DOUBLE_BRACKET_END',

  TEXT = 'TEXT',
  BOLD = 'BOLD',
  ITALIC = 'ITALIC',
  UNDERLINE = 'UNDERLINE',
  STRIKETHROUGH = 'STRIKETHROUGH',
  CODE = 'CODE',
  SUPERSCRIPT = 'SUPERSCRIPT',
  SUBSCRIPT = 'SUBSCRIPT',
  HIGHLIGHT = 'HIGHLIGHT',
  INLINE_STYLE = 'INLINE_STYLE',

  LINK_START = 'LINK_START',
  LINK_END = 'LINK_END',
  LINK_REF_DEF = 'LINK_REF_DEF',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  EMBED = 'EMBED',
  FILE = 'FILE',

  VARIABLE = 'VARIABLE',
  GLOBAL_VARIABLE = 'GLOBAL_VARIABLE',
  EXPRESSION = 'EXPRESSION',
  INCLUDE = 'INCLUDE',

  ATTRIBUTES_START = 'ATTRIBUTES_START',
  ATTRIBUTES_END = 'ATTRIBUTES_END',

  ESCAPE = 'ESCAPE',
  COMMENT_INLINE = 'COMMENT_INLINE',
  ABBREVIATION = 'ABBREVIATION',
  ANCHOR = 'ANCHOR',
  FOOTNOTE_DEF = 'FOOTNOTE_DEF',
  ATTRIBUTE_SHORTCUT = 'ATTRIBUTE_SHORTCUT',
}

export interface Token {
  type: TokenType;
  value: string;
  line: number;
  column: number;
  length: number;
}
